  project:
    type: website
    output-dir: _site
    resources:
      - Images/**
      - Dataout/**
  
  website:
    title: ""  # Leave title blank or very short to suppress default
    navbar:
      logo: Images/emblem_moz_med.png
      background: "#f8f9fa"
  
  format:
    html:
      theme: cosmo
      toc: true
      toc-title: "Conteúdo"
  include-in-header:
    - text: |
        <style>
          .navbar-brand img {
            max-height: 80px;  /* Increase from default (often ~40–50px) */
            padding-right: 10px;
          }
  
          .custom-navbar-title {
            font-family: var(--bs-body-font-family);
            font-size: 2.2rem;        /* ⬅️ increase text size */
            font-weight: 600;         /* ⬅️ make it bolder */
            line-height: 1.1;
            line-height: 1.3;
            color: #333333;
            padding-left: 10px;
            display: flex;               /* Ensure stacking */
            flex-direction: column; 
            margin: 0;
          }
  
          .custom-navbar-title small {
              font-size: 1.2rem;        /* ⬅️ make subtitle larger too */
              font-weight: 350;
              color: #555555;
              line-height: 1;
              margin: 0;
          }
  
          .navbar-brand {
            display: flex;
            align-items: center;
          }
        </style>
  
        <script>
          window.addEventListener('DOMContentLoaded', () => {
            const brand = document.querySelector('.navbar-brand');
            if (brand) {
              brand.innerHTML += `<div class="custom-navbar-title">
                <span>Direcção Nacional de Saúde Pública</span>
                <small>Ministério da Saúde de Moçambique</small>
              </div>`;
            }
          });
        </script>
