# project:
#   type: default
# metadata-files:
#   - _brand.yml
# format:
#   html:
#     theme: cosmo
#     toc: true
#     toc-title: "Conteúdo"
project:
  type: website

website:
  title: "DNSP PES 2026"
  navbar:
    logo: Images/emblem_moz_xsmall.png
    background: "#FFF4E1"

format:
  html:
    theme: cosmo
    toc: true
    toc-title: "Conteúdo"
    include-in-header:
      - text: |
          <style>
            .navbar-brand img {
              max-height: 75px;
              padding-right: 10px;
            }
          </style>

metadata-files:
  - _brand.yml
