name: Generate PESOE Excel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # Every day at 05:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev

      - name: Install R packages
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); install.packages(c(
            "ggplot2", "tibble", "tidyr", "readr", "purrr", "dplyr", "stringr", "forcats",  # tidyverse
            "ggthemes", "robotoolbox", "dm", "haven", "gt", "glue", "openxlsx", "scales", "lubridate"
          ))'

      - name: Ensure Dataout directory exists
        run: mkdir -p Dataout

      - name: Run script
        env:
          KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }}
        run: Rscript Scripts/pesoe.R

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push new Excel file
        run: |
          git add Dataout/*.xlsx
          git commit -m "Add new PESOE Excel file for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
